### ISSUE TITLE
使用 DHDAXCW/lede 编译r5s失败

### ISSUE THREAD

**Issue by zhangguanzhang** [DHDAXCW/NanoPi-R5S#1]
```
    ERROR: package/boot/uboot-rockchip failed to build (build variant: nanopi-r5s-rk3568).
make -r package/compile: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/workdir/openwrt/include/toplevel.mk:230: package/compile] Error 1
```

详细日志：
```
make[2]: Entering directory '/workdir/openwrt/package/boot/uboot-rockchip'
mkdir -p /workdir/openwrt/dl
SHELL= flock /workdir/openwrt/tmp/.u-boot-2022.07.tar.bz2.flock -c '  	/workdir/openwrt/scripts/download.pl "/workdir/openwrt/dl" "u-boot-2022.07.tar.bz2" "92b08eb49c24da14c1adbf70a71ae8f37cc53eeb4230e859ad8b6733d13dcf5e" "" "https://mirror.cyberbits.eu/u-boot" "https://ftp.denx.de/pub/u-boot" "ftp://ftp.denx.de/pub/u-boot"    '
rm -f /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r5s-rk3568/u-boot-2022.07/.built
touch /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r5s-rk3568/u-boot-2022.07/.built_check
make  -C /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r5s-rk3568/u-boot-2022.07 CROSS_COMPILE=aarch64-openwrt-linux-musl- DTC="/workdir/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.19/scripts/dtc/dtc" HOSTCC="ccache gcc" HOSTCFLAGS="-O2 -I/workdir/openwrt/staging_dir/host/include -I/workdir/openwrt/staging_dir/hostpkg/include -I/workdir/openwrt/staging_dir/target-aarch64_generic_musl/host/include -I/workdir/openwrt/staging_dir/host/include -I/workdir/openwrt/staging_dir/hostpkg/include -I/workdir/openwrt/staging_dir/target-aarch64_generic_musl/host/include -std=gnu11" HOSTLDFLAGS="-L/workdir/openwrt/staging_dir/host/lib -L/workdir/openwrt/staging_dir/hostpkg/lib -L/workdir/openwrt/staging_dir/target-aarch64_generic_musl/host/lib" V='' BL31=/workdir/openwrt/staging_dir/target-aarch64_generic_musl/image/rk3568_bl31_v1.24.elf
make[3]: Entering directory '/workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r5s-rk3568/u-boot-2022.07'
===================== WARNING ======================
This board uses CONFIG_SPL_FIT_GENERATOR. Please migrate
to binman instead, to avoid the proliferation of
arch-specific scripts with no tests.
====================================================
  CFGCHK  u-boot.cfg
  OFCHK   .config
  ENVC    include/generated/env.txt
  ENVP    include/generated/env.in
  ENVT    include/generated/environment.h
  CC      env/common.o
  AR      env/built-in.o
  CC      lib/efi_loader/dtbdump.o
  LD      lib/efi_loader/dtbdump_efi.so
  OBJCOPY lib/efi_loader/dtbdump.efi
  CC      lib/efi_loader/initrddump.o
  LD      lib/efi_loader/initrddump_efi.so
  OBJCOPY lib/efi_loader/initrddump.efi
  LD      u-boot
  OBJCOPY u-boot.srec
  SYM     u-boot.sym
  OBJCOPY u-boot-nodtb.bin
  RELOC   u-boot-nodtb.bin
  MKIMAGE u-boot.img
  MKIMAGE u-boot-dtb.img
  CAT     u-boot-dtb.bin
  COPY    u-boot.bin
./"arch/arm/mach-rockchip/make_fit_atf.py" \
arch/arm/dts/rk3568-nanopi-r5s.dtb > u-boot.its
Traceback (most recent call last):
  File "./arch/arm/mach-rockchip/make_fit_atf.py", line 267, in <module>
    main()
  File "./arch/arm/mach-rockchip/make_fit_atf.py", line 262, in main
    generate_atf_fit_dts(fit_its, bl31_elf, tee_file, uboot_elf, dtbs)
  File "./arch/arm/mach-rockchip/make_fit_atf.py", line 158, in generate_atf_fit_dts
    generate_atf_fit_dts_bl31(fit_file, bl31_file_name, tee_file_name, dtbs_file_name)
  File "./arch/arm/mach-rockchip/make_fit_atf.py", line 134, in generate_atf_fit_dts_bl31
    segments = unpack_elf(bl31_file_name)
  File "./arch/arm/mach-rockchip/make_fit_atf.py", line 178, in unpack_elf
    with open(filename, 'rb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/workdir/openwrt/staging_dir/target-aarch64_generic_musl/image/rk3568_bl31_v1.24.elf'
make[3]: *** [Makefile:1382: u-boot.its] Error 1
make[3]: *** Deleting file 'u-boot.its'
make[2]: *** [Makefile:207: /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r5s-rk3568/u-boot-2022.07/.built] Error 2
make[3]: Leaving directory '/workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r5s-rk3568/u-boot-2022.07'
make[2]: Leaving directory '/workdir/openwrt/package/boot/uboot-rockchip'
time: package/boot/uboot-rockchip/nanopi-r5s-rk3568/compile#2.43#1.19#3.52
    ERROR: package/boot/uboot-rockchip failed to build (build variant: nanopi-r5s-rk3568).
make[1]: *** [package/Makefile:116: package/boot/uboot-rockchip/compile] Error 1
```

**Comment by DHDAXCW** [comment]
已修复了，重新编译，因为丢了ATF路径

**Comment by zhangguanzhang** [comment]
我试试

**Comment by zhangguanzhang** [comment]
看样子好了
