### ISSUE TITLE
No such file or directory: '/workdir/openwrt/staging_dir/target-aarch64_generic_musl/image/rk3568_bl31_v1.24.elf'

### ISSUE THREAD

**Issue by zhangguanzhang** [DHDAXCW/NanoPi-R5S#3]
最新提交 e881a068da71349c5e9e3bbc34db8bc6e9c56e7c

```
mkdir -p /workdir/openwrt/dl
SHELL= flock /workdir/openwrt/tmp/.arm-trusted-firmware-rockchip-vendor-2022-08-01-b0c100f1.tar.xz.flock -c '  	/workdir/openwrt/scripts/download.pl "/workdir/openwrt/dl" "arm-trusted-firmware-rockchip-vendor-2022-08-01-b0c100f1.tar.xz" "17723ac8f6ec446c759444ee29ba4fe544cebb3785e26d8e10c91c54b9df3f1a" "" || (  /workdir/openwrt/scripts/dl_github_archive.py --dl-dir="/workdir/openwrt/dl" --url="https://github.com/rockchip-linux/rkbin.git" --version="b0c100f1a260d807df450019774993c761beb79d" --subdir="arm-trusted-firmware-rockchip-vendor-2022-08-01-b0c100f1" --source="arm-trusted-firmware-rockchip-vendor-2022-08-01-b0c100f1.tar.xz" --hash="17723ac8f6ec446c759444ee29ba4fe544cebb3785e26d8e10c91c54b9df3f1a" || ( 	echo "Checking out files from the git repository..."; mkdir -p /workdir/openwrt/tmp/dl && cd /workdir/openwrt/tmp/dl && rm -rf arm-trusted-firmware-rockchip-vendor-2022-08-01-b0c100f1 && [ \! -d arm-trusted-firmware-rockchip-vendor-2022-08-01-b0c100f1 ] && git clone  https://github.com/rockchip-linux/rkbin.git arm-trusted-firmware-rockchip-vendor-2022-08-01-b0c100f1 && (cd arm-trusted-firmware-rockchip-vendor-2022-08-01-b0c100f1 && git checkout b0c100f1a260d807df450019774993c761beb79d && git submodule update --init --recursive) && echo "Packing checkout..." && export TAR_TIMESTAMP=`cd arm-trusted-firmware-rockchip-vendor-2022-08-01-b0c100f1 && git log -1 --format='\''@%ct'\''` && rm -rf arm-trusted-firmware-rockchip-vendor-2022-08-01-b0c100f1/.git && 	tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c arm-trusted-firmware-rockchip-vendor-2022-08-01-b0c100f1 | 	xz -zc -7e > /workdir/openwrt/tmp/dl/arm-trusted-firmware-rockchip-vendor-2022-08-01-b0c100f1.tar.xz && mv /workdir/openwrt/tmp/dl/arm-trusted-firmware-rockchip-vendor-2022-08-01-b0c100f1.tar.xz /workdir/openwrt/dl/ && rm -rf arm-trusted-firmware-rockchip-vendor-2022-08-01-b0c100f1; );  )    '
make[2]: Leaving directory '/workdir/openwrt/package/boot/arm-trusted-firmware-rockchip-vendor'
time: package/boot/arm-trusted-firmware-rockchip-vendor/rk3568/compile#0.18#0.11#0.27
make[2]: Entering directory '/workdir/openwrt/package/boot/uboot-envtools'
mkdir -p /workdir/openwrt/dl
SHELL= flock /workdir/openwrt/tmp/.u-boot-2021.01.tar.bz2.flock -c '  	/workdir/openwrt/scripts/download.pl "/workdir/openwrt/dl" "u-boot-2021.01.tar.bz2" "b407e1510a74e863b8b5cb42a24625344f0e0c2fc7582d8c866bd899367d0454" "" "https://ftp.denx.de/pub/u-boot" "https://mirror.cyberbits.eu/u-boot" "ftp://ftp.denx.de/pub/u-boot"    '
touch /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/.prepared_e4a03552d2792e4f927deda2d9bacb57_6664517399ebbbc92a37c5bb081b5c53_check
. /workdir/openwrt/include/shell.sh; bzcat /workdir/openwrt/dl/u-boot-2021.01.tar.bz2 | tar -C /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01

Applying ./patches/001-compile.patch using plaintext: 
patching file tools/env/Makefile
touch /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/.prepared_e4a03552d2792e4f927deda2d9bacb57_6664517399ebbbc92a37c5bb081b5c53
rm -f /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/.configured_*
rm -f /workdir/openwrt/staging_dir/target-aarch64_generic_musl/stamp/.uboot-envtools_installed
touch /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/include/config.h
mkdir -p /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/include/config
touch /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/include/config/auto.conf
mkdir -p /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/include/generated
touch /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/include/generated/autoconf.h
touch /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/.configured_68b329da9893e34099c7d8ad5cb9c940
rm -f /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/.built
touch /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/.built_check
CFLAGS="-Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01=u-boot-2021.01 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/workdir/openwrt/staging_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/usr/include -I/workdir/openwrt/staging_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/include/fortify -I/workdir/openwrt/staging_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/include " CXXFLAGS="-Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01=u-boot-2021.01 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/workdir/openwrt/staging_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/usr/include -I/workdir/openwrt/staging_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/include/fortify -I/workdir/openwrt/staging_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/include " LDFLAGS="-L/workdir/openwrt/staging_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/lib -znow -zrelro " make  -C /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/. AR="aarch64-openwrt-linux-musl-gcc-ar" AS="ccache_cc -c -Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01=u-boot-2021.01 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=aarch64-openwrt-linux-musl-ld NM="aarch64-openwrt-linux-musl-gcc-nm" CC="ccache_cc" GCC="ccache_cc" CXX="ccache_cxx" RANLIB="aarch64-openwrt-linux-musl-gcc-ranlib" STRIP=aarch64-openwrt-linux-musl-strip OBJCOPY=aarch64-openwrt-linux-musl-objcopy OBJDUMP=aarch64-openwrt-linux-musl-objdump SIZE=aarch64-openwrt-linux-musl-size CROSS="aarch64-openwrt-linux-musl-" ARCH="aarch64" TARGET_CFLAGS="-Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01=u-boot-2021.01 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" TARGET_LDFLAGS="-L/workdir/openwrt/staging_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-aarch64_generic_gcc-8.4.0_musl/lib -znow -zrelro" no-dot-config-targets=envtools envtools ;
make[3]: Entering directory '/workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01'
  HOSTCC  scripts/basic/fixdep
  UPD     include/config/uboot.release
  UPD     include/generated/version_autogenerated.h
  UPD     include/generated/timestamp_autogenerated.h
  COPY    tools/version.h
  LD      tools/env/built-in.o
  HOSTCC  tools/env/crc32.o
  HOSTCC  tools/env/ctype.o
  HOSTCC  tools/env/env_attr.o
  HOSTCC  tools/env/env_flags.o
  HOSTCC  tools/env/fw_env.o
  HOSTCC  tools/env/linux_string.o
  AR      tools/env/lib.a
  HOSTCC  tools/env/fw_env_main.o
  HOSTLD  tools/env/fw_printenv
  STRIP   tools/env/fw_printenv
make[3]: Leaving directory '/workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01'
touch /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/.built
rm -rf /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/.pkgdir/uboot-envtools.installed /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/.pkgdir/uboot-envtools
mkdir -p /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/.pkgdir/uboot-envtools
install -d -m0755 /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/.pkgdir/uboot-envtools/usr/sbin
install -m0755 /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/tools/env/fw_printenv /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/.pkgdir/uboot-envtools/usr/sbin
ln -sf fw_printenv /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/.pkgdir/uboot-envtools/usr/sbin/fw_setenv
install -m0755 ./files/fw_printsys /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/.pkgdir/uboot-envtools/usr/sbin
install -m0755 ./files/fw_setsys /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/.pkgdir/uboot-envtools/usr/sbin
install -d -m0755 /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/.pkgdir/uboot-envtools/lib
install -m0644 ./files/uboot-envtools.sh /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/.pkgdir/uboot-envtools/lib
install -d -m0755 /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/.pkgdir/uboot-envtools/etc/uci-defaults
touch /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/.pkgdir/uboot-envtools.installed
mkdir -p /workdir/openwrt/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp
SHELL= flock /workdir/openwrt/tmp/.root-copy.flock -c 'cp -fpR /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/.pkgdir/uboot-envtools/. /workdir/openwrt/staging_dir/target-aarch64_generic_musl/root-rockchip/'
touch /workdir/openwrt/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp/.uboot-envtools_installed
mkdir -p /workdir/openwrt/bin/targets/rockchip/armv8/packages /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/ipkg-aarch64_generic/uboot-envtools/CONTROL /workdir/openwrt/staging_dir/target-aarch64_generic_musl/pkginfo
install -d -m0755 /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/ipkg-aarch64_generic/uboot-envtools/usr/sbin
install -m0755 /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/tools/env/fw_printenv /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/ipkg-aarch64_generic/uboot-envtools/usr/sbin
ln -sf fw_printenv /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/ipkg-aarch64_generic/uboot-envtools/usr/sbin/fw_setenv
install -m0755 ./files/fw_printsys /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/ipkg-aarch64_generic/uboot-envtools/usr/sbin
install -m0755 ./files/fw_setsys /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/ipkg-aarch64_generic/uboot-envtools/usr/sbin
install -d -m0755 /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/ipkg-aarch64_generic/uboot-envtools/lib
install -m0644 ./files/uboot-envtools.sh /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/ipkg-aarch64_generic/uboot-envtools/lib
install -d -m0755 /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/ipkg-aarch64_generic/uboot-envtools/etc/uci-defaults
find /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/ipkg-aarch64_generic/uboot-envtools -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
export CROSS="aarch64-openwrt-linux-musl-"  NO_RENAME=1 ; NM="aarch64-openwrt-linux-musl-nm" STRIP="/workdir/openwrt/staging_dir/host/bin/sstrip -z" STRIP_KMOD="/workdir/openwrt/scripts/strip-kmod.sh" PATCHELF="/workdir/openwrt/staging_dir/host/bin/patchelf" /workdir/openwrt/scripts/rstrip.sh /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/ipkg-aarch64_generic/uboot-envtools
rstrip.sh: /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/ipkg-aarch64_generic/uboot-envtools/usr/sbin/fw_printenv: executable
(cd /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/ipkg-aarch64_generic/uboot-envtools/CONTROL; ( echo "$CONTROL"; printf "Description: "; echo "$DESCRIPTION" | sed -e 's,^[[:space:]]*, ,g'; ) > control; chmod 644 control; ( echo "#!/bin/sh"; echo "[ \"\${IPKG_NO_SCRIPT}\" = \"1\" ] && exit 0"; echo "[ -s "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_postinst \$0 \$@"; ) > postinst; ( echo "#!/bin/sh"; echo "[ -s "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_prerm \$0 \$@"; ) > prerm; chmod 0755 postinst prerm; echo "$V_Package_uboot_envtools_conffiles" > conffiles;  )
install -d -m0755 /workdir/openwrt/bin/targets/rockchip/armv8/packages
/workdir/openwrt/staging_dir/host/bin/fakeroot /workdir/openwrt/scripts/ipkg-build -m "" /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/ipkg-aarch64_generic/uboot-envtools /workdir/openwrt/bin/targets/rockchip/armv8/packages
/workdir/openwrt/staging_dir/host/bin/find: '/workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/ipkg-aarch64_generic/uboot-envtools/etc/config/ubootenv': No such file or directory
/workdir/openwrt/staging_dir/host/bin/find: '/workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/ipkg-aarch64_generic/uboot-envtools/etc/fw_env.config': No such file or directory
/workdir/openwrt/staging_dir/host/bin/find: '/workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/ipkg-aarch64_generic/uboot-envtools/etc/fw_sys.config': No such file or directory
Packaged contents of /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-2021.01/ipkg-aarch64_generic/uboot-envtools into /workdir/openwrt/bin/targets/rockchip/armv8/packages/uboot-envtools_2021.01-20_aarch64_generic.ipk
echo "uboot-envtools" >> /workdir/openwrt/staging_dir/target-aarch64_generic_musl/pkginfo/uboot-envtools.default.install
make[2]: Leaving directory '/workdir/openwrt/package/boot/uboot-envtools'
time: package/boot/uboot-envtools/compile#4.01#1.02#4.38
make[2]: Entering directory '/workdir/openwrt/package/boot/uboot-rockchip'
mkdir -p /workdir/openwrt/dl
SHELL= flock /workdir/openwrt/tmp/.u-boot-2022.07.tar.bz2.flock -c '  	/workdir/openwrt/scripts/download.pl "/workdir/openwrt/dl" "u-boot-2022.07.tar.bz2" "92b08eb49c24da14c1adbf70a71ae8f37cc53eeb4230e859ad8b6733d13dcf5e" "" "https://mirror.cyberbits.eu/u-boot" "https://ftp.denx.de/pub/u-boot" "ftp://ftp.denx.de/pub/u-boot"    '
rm -f /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r5s-rk3568/u-boot-2022.07/.built
touch /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r5s-rk3568/u-boot-2022.07/.built_check
make  -C /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r5s-rk3568/u-boot-2022.07 CROSS_COMPILE=aarch64-openwrt-linux-musl- DTC="/workdir/openwrt/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux-5.19/scripts/dtc/dtc" HOSTCC="ccache gcc" HOSTCFLAGS="-O2 -I/workdir/openwrt/staging_dir/host/include -I/workdir/openwrt/staging_dir/hostpkg/include -I/workdir/openwrt/staging_dir/target-aarch64_generic_musl/host/include -I/workdir/openwrt/staging_dir/host/include -I/workdir/openwrt/staging_dir/hostpkg/include -I/workdir/openwrt/staging_dir/target-aarch64_generic_musl/host/include -std=gnu11" HOSTLDFLAGS="-L/workdir/openwrt/staging_dir/host/lib -L/workdir/openwrt/staging_dir/hostpkg/lib -L/workdir/openwrt/staging_dir/target-aarch64_generic_musl/host/lib" V='' BL31=/workdir/openwrt/staging_dir/target-aarch64_generic_musl/image/rk3568_bl31_v1.24.elf
make[3]: Entering directory '/workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r5s-rk3568/u-boot-2022.07'
===================== WARNING ======================
This board uses CONFIG_SPL_FIT_GENERATOR. Please migrate
to binman instead, to avoid the proliferation of
arch-specific scripts with no tests.
====================================================
  CFGCHK  u-boot.cfg
  OFCHK   .config
  ENVC    include/generated/env.txt
  ENVP    include/generated/env.in
  ENVT    include/generated/environment.h
  CC      env/common.o
  AR      env/built-in.o
  CC      lib/efi_loader/dtbdump.o
  LD      lib/efi_loader/dtbdump_efi.so
  OBJCOPY lib/efi_loader/dtbdump.efi
  CC      lib/efi_loader/initrddump.o
  LD      lib/efi_loader/initrddump_efi.so
  OBJCOPY lib/efi_loader/initrddump.efi
  LD      u-boot
  OBJCOPY u-boot.srec
  SYM     u-boot.sym
  OBJCOPY u-boot-nodtb.bin
  RELOC   u-boot-nodtb.bin
  MKIMAGE u-boot.img
  MKIMAGE u-boot-dtb.img
  CAT     u-boot-dtb.bin
  COPY    u-boot.bin
./"arch/arm/mach-rockchip/make_fit_atf.py" \
arch/arm/dts/rk3568-nanopi-r5s.dtb > u-boot.its
Traceback (most recent call last):
  File "./arch/arm/mach-rockchip/make_fit_atf.py", line 267, in <module>
    main()
  File "./arch/arm/mach-rockchip/make_fit_atf.py", line 262, in main
    generate_atf_fit_dts(fit_its, bl31_elf, tee_file, uboot_elf, dtbs)
  File "./arch/arm/mach-rockchip/make_fit_atf.py", line 158, in generate_atf_fit_dts
    generate_atf_fit_dts_bl31(fit_file, bl31_file_name, tee_file_name, dtbs_file_name)
  File "./arch/arm/mach-rockchip/make_fit_atf.py", line 134, in generate_atf_fit_dts_bl31
    segments = unpack_elf(bl31_file_name)
  File "./arch/arm/mach-rockchip/make_fit_atf.py", line 178, in unpack_elf
    with open(filename, 'rb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/workdir/openwrt/staging_dir/target-aarch64_generic_musl/image/rk3568_bl31_v1.24.elf'
make[3]: *** [Makefile:1382: u-boot.its] Error 1
make[3]: *** Deleting file 'u-boot.its'
make[2]: *** [Makefile:207: /workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r5s-rk3568/u-boot-2022.07/.built] Error 2
make[3]: Leaving directory '/workdir/openwrt/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r5s-rk3568/u-boot-2022.07'
make[2]: Leaving directory '/workdir/openwrt/package/boot/uboot-rockchip'
time: package/boot/uboot-rockchip/nanopi-r5s-rk3568/compile#2.45#1.17#3.51
    ERROR: package/boot/uboot-rockchip failed to build (build variant: nanopi-r5s-rk3568).
make[1]: *** [package/Makefile:116: package/boot/uboot-rockchip/compile] Error 1
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: package/compile] Error 2
```

**Comment by DHDAXCW** [comment]
已修复
